### ISSUE TITLE
Add a method to fetch all price

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/fetch-api-service#5]
### Is your feature request related to a problem?

Currently, we need to specify all ucids to fetch information.
Could you please add an api to fetch all ucids

### Describe the solution you'd like

So instead of to do this:
```https://fas.archethic.net/api/v1/quotes/latest?ucids=1027,3890,1839,3408,20920```
Could you provide price for all ucids available in api service:
```https://fas.archethic.net/api/v1/quotes/latest```

**Comment by bchamagne** [comment]
done: 8b74cc5
